### ISSUE TITLE
EditMonitors

### ISSUE THREAD

**Issue by gconcepts** [bitfield/uptimerobot#9]
Could you please implement an edit monitor feature so monitoring can be paused and unpaused?

**Comment by bitfield** [comment]
Good idea! How about a `pause` and `unpause` command? Would that be helpful?

**Comment by gconcepts** [comment]
Yes that would definitely be helpful.

Thanks a ton.

**Comment by bitfield** [comment]
@gconcepts, I've added `pause` and `start` commands in `v0.9.0`. Let me know if it works for you!

**Comment by gconcepts** [comment]
@bitfield Sorry for the delay. Just tested and it works as expected and advertised.

Thanks a ton for this.
